### ISSUE TITLE
Minimum deployment target to iOS 8.0

### ISSUE THREAD

**Issue by vadimb** [justeat/JustLog#1]
Hi,
is there anything that could prevent us from lowering the deployment target to iOS 8.0 ? It seems that both libs(SwiftyBeaver,CocoaAsyncSocket) support iOS 8.0.

**Comment by albertodebortoli** [comment]
@vadimb I believe we can support 8.0 without any code change.
Reason why we haven't done it is that we develop against 9.0 for all the components at Just Eat but we would accept a pull request if that helps.

**Comment by vadimb** [comment]
#7

**Comment by vadimb** [comment]
Sorry for late response @albertodebortoli . I changed it in #7

**Comment by albertodebortoli** [comment]
@vadimb Thanks. This is now publicly available in trunk (v 1.1.0).
