### ISSUE TITLE
[Crash] Over committing from RepeatingTimer

### ISSUE THREAD

**Issue by freak4pc** [justeat/JustLog#114]
Hey there, 
We noticed there's a somewhat repeating crash on JustLog that looks like this:

```
Crashed: com.apple.root.default-qos.overcommit
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000000
```

<img width="914" alt="image" src="https://user-images.githubusercontent.com/605076/132574415-af7be934-b15b-424a-a26e-2e411066815f.png">

Over-comitting basically means the queue can't handle the amount of scheduled pieces of work simultaneously with the provided quality of service. I believe this is related to the fact you're using `makeTimerSource` and using the default queue instead of possibly creating your own queue with a different quality of service, but haven't had a chance to properly investigate.

Are you aware of this crash? Couldn't find any other reports on it. Thanks!

**Comment by albertodebortoli** [comment]
Hi @freak4pc, I'm sorry the team didn't address this. I don't think we have encountered this specific crash in our apps.
I'm gonna go ahead and close this as we are deprecating the component and archiving the repo.
