### ISSUE TITLE
Code=28 "No space left on device"

### ISSUE THREAD

**Issue by zixzelz** [justeat/JustLog#120]
Hi everyone,

Found an issue 
`🔌 <LogstashDestination>, 1998045481163 did error: The operation couldn’t be completed. No space left on device`
`Error Domain=NSPOSIXErrorDomain Code=28 "No space left on device" UserInfo={_kCFStreamErrorCodeKey=28, _kCFStreamErrorDomainKey=1}`

Xcode 13.1, iOS 15.1

How to reproduce:
After sending approximately 500 request with logs, next requests do not sending.

Why:
As I can see in "LogstashDestinationSocket" we create task "streamTask(withHostName: self.host, port: self.port)" , then write data in task, then resume it. But, this task will not never cancel in future, and itwill live for all time of living URLSession, or for all time of living app. When will be created about 500 task, we will have an error.
Count of created tasks we can check by "session.getAllTasks". All tasks will have status "running"

To fix it I think we can add "task.cancel()" in "dispatchGroup.notify".

```
dispatchGroup.notify(queue: queue) {
    task.cancel()
    complete(sendStatus)
}
```
or
```
dispatchGroup.notify(queue: queue) {
    task.closeWrite()
    task.closeRead()
    complete(sendStatus)
}
```

**Comment by albertodebortoli** [comment]
Sorted with #123 and published in version 4.0.1.
