### ISSUE TITLE
Logs are not shown correctly in Kibana

### ISSUE THREAD

**Issue by sebnil** [justeat/JustLog#127]
Config:
![image](https://user-images.githubusercontent.com/1711012/200997420-57209909-7365-4e41-8c4c-4a352d00558f.png)

This is what I see in Kibana:
![image](https://user-images.githubusercontent.com/1711012/200997295-4de64067-a7e4-4c0b-b004-7b1cb67c306b.png)

I am using the ELK stack from here:
https://github.com/deviantony/docker-elk

Why is the log message all in bytes? I expected a json like view. Are certain codec settings in Kibana necessary to get JustLog to work?

**Comment by marianatkach** [comment]
Hi,
I have same problems with display logs in my stack. 
I get something like this:

"x16\x03\x01\x02\x00\x01\x00\x01\xfc\x03\x03\xfbp\xba\xf6\x93P\xafsL\x8489\xb6\xba\x14\\\xf2_\x8a~\xc5E\xbf\x98\xfc\xce\t\xe4\xfcJ\xf9\x8b \xec\x02\x8c"\x8c\x1c:{D\xe6\xb7[\xbc"i\xed*4\xcc\xebu&\x1cx1\xd2#\x8d\xe3\x83\xd2<\x00*\xda\xda\x13\x01\x13\x02\x13\x03\xc0,\xc0+\xcc\xa9\xc00\xc0/\xcc\xa8\xc0\n\xc0\t\xc0\x14\xc0\x13\x00\x9d\x00\x9c\x005\x00/\xc0\x08\xc0\x12\x00\n\x01\x00\x01\x89ZZ\x00\x00\x00\x17\x00\x00\xff\x01\x00\x01\x00\x00\n\x00\x0c\x00\n\n\n\x00\x1d\x00\x17...."

I have one variant about this - here using ssl encrypted. And i can't use this in custom stack ELK. Maybe, i can't understand something? How i can use this?

**Comment by albertodebortoli** [comment]
Hi @sebnil and @marianatkach, I'm sorry the team didn't address this.
I'm gonna go ahead and close this as we are deprecating the component and archiving the repo.
