### ISSUE TITLE
Proposal: Smaller API

### ISSUE THREAD

**Issue by RuiAAPeres** [justeat/JustLog#16]
We are currently using JustLog in our project, but we find the current API area quite extensive:

```swift
public protocol Logging {

    public func verbose(_ message: String, error: NSError?, userInfo: [String : Any]?, _ file: StaticString, _ function: StaticString, _ line: UInt)

    public func debug(_ message: String, error: NSError?, userInfo: [String : Any]?, _ file: StaticString, _ function: StaticString, _ line: UInt)

    public func info(_ message: String, error: NSError?, userInfo: [String : Any]?, _ file: StaticString, _ function: StaticString, _ line: UInt)

    public func warning(_ message: String, error: NSError?, userInfo: [String : Any]?, _ file: StaticString, _ function: StaticString, _ line: UInt)

    public func error(_ message: String, error: NSError?, userInfo: [String : Any]?, _ file: StaticString, _ function: StaticString, _ line: UInt)
}
```

To make it easier for us, we created a wrapper around the `Logging` protocol like so:

```swift
extension BabylonLogging {
    func log(_ level: LogLevel,
              _ message: String,
              error: Error?,
              userInfo: [String : Any]?,
              _ file: StaticString,
              _ function: StaticString,
              _ line: UInt)
}
```

Where the key bit is the `LogLevel`: 

```swift
public enum LogLevel {
    case verbose
    case debug
    case info
    case warning
    case error
}
```

This is just a minor thing, but do you think it would make sense to have the same in JustLog? I am happy to make a PR.

**Comment by albertodebortoli** [comment]
@RuiAAPeres opinable but agreeable! Happy to accept a PR.

**Comment by oronbz** [comment]
@albertodebortoli @RuiAAPeres just note that this should be in addition to the current API to properly support Objective-C as well. Because Obj-C doesn't support Swift enums.

**Comment by ghost** [comment]
Hey @RuiAAPeres, we've discussed this for a while and feel that this may be better kept as an external extension on the existing API.

If we were to add this, we would have to reverse the pattern here - i.e. have the level-specific methods call the more generic "log" method. However, as this has only been requested for convenience / syntactic sugar, we feel using an extension outside the library is probably a better approach.

If anything, this also allows you to customise it as you see fit and so doesn't make any assumptions about any other use cases.

**Comment by ghost** [comment]
I'll leave this open for a few days for further comment and close after that.
