### ISSUE TITLE
Logstash ssl error

### ISSUE THREAD

**Issue by arjunattam** [justeat/JustLog#17]
Logging through logstash is unreliable - works for some time and not for the rest. The library shows these errors in the console:

```
Error in postLogs: Optional(Error Domain=kCFStreamErrorDomainSSL Code=-9806 "(null)" UserInfo={NSLocalizedRecoverySuggestion=Error code definition can be found in Apple's SecureTransport.h})
```

```
🔌 <AsyncSocket>, Could not connect: Attempting to connect while connected or accepting connections. Disconnect first.
🔌 <AsyncSocket>, Could not startTLS: The operation couldn't be completed. (JustLog.AsyncSocketManager.AsyncSocketError error 0.)
Error in postLogs: Optional(Error Domain=NSPOSIXErrorDomain Code=0 "Undefined error: 0" UserInfo={NSLocalizedDescription=Undefined error: 0, NSLocalizedFailureReason=Error in connect() function})
```

Restarting logstash seems to fix the issue, which suggests there's something wrong with the logstash config (shown below). Any suggestions on what could be wrong? I'm on logstash 5.1.1

```
    tcp {
        port => "19540"
        tags => ["input_ios_sdk"]
        ssl_enable => true
        ssl_cert => "/path/to/domain.com.crt"
        ssl_key => "/path/to/wild.domain.com.key"
        ssl_verify => false
    }
```

Thanks for the good work on the library!

**Comment by ghost** [comment]
Hey this is probably a question more suited to the nginx team (assuming that the above is nginx config).

Sorry we can't help you further @arjun27, but if you're discover the answer please do post back here for the benefit of others :)

**Comment by shayneoneill** [comment]
Did you ever work this out?
