### ISSUE TITLE
Is this still maintained? Looking for collaborators?

### ISSUE THREAD

**Issue by oronbz** [justeat/JustLog#20]
Hi Guys,
I've started using `JustLog` and it kind of fit my needs so many thanks on the great work you've done here. I didn't find any other `Logz.io` solution for iOS other than implementing it myself.

But I've noticed you're not very active on PRs and issues. Do you need any help with maintaining this library? Should I fork it and maintain it on my own?

There are a few things I'd like to improve and fix in this library.
Please let me know the best way to continue with this.

Thanks,
Oron

**Comment by marcospolanco** [comment]
Listening in as well. Thx, @ilazakis.

**Comment by ghost** [comment]
Hi both, @oronbz @marcospolanco  this is the library we use internally at Just Eat currently on the UK app and rest assured we are maintaining it 100%. Reason why it doesn't look particularly under development its that the current version already fulfils our needs but we have some changes lined up to improve the logging of `NSError`s (as it's an internal need) that we plan to add in the coming days. External collaborators are always welcome as long as the changes stick to the goal of the library.

**Comment by ghost** [comment]
@oronbz @marcospolanco we released version 1.3.0 with better support for error logging. So... yes, this library is very much still maintained (just like all the iOS libraries we develop at Just Eat) 😊
Will close the issue.
