### ISSUE TITLE
Implement CocoaAsyncSocket 7.6.1

### ISSUE THREAD

**Issue by molynerd** [justeat/JustLog#24]
I'd like to use this for my project, but this pod depends on CocoaAsyncSocket 7.5.0 and I'm already depending on 7.6.1. 

I'd love to help out if possible, but it doesn't appear that the files are complete. There appears to be no way to open this project. That could just be my inexperience with developing pods. Let me know.

**Comment by molynerd** [comment]
Wait... I think I figured it out. If I can get it updated, I'll submit a PR.

**Comment by molynerd** [comment]
I'm not seeing any problems with using 7.6.1. Are there any tests you have to validate?

**Comment by molynerd** [comment]
All tests in [Tests](https://github.com/justeat/JustLog/tree/master/Example/Tests) passed, though they don't appear to be directly testing the socket implementation. Let me know if there's something else you'd want to validate here.

**Comment by ghost** [comment]
Hi @molynerd sorry for the delay in response! The change is in the master branch now and available in version 1.3.1 via Cocoapods.
