### ISSUE TITLE
commit 303aaf7 - compilation error 

### ISSUE THREAD

**Issue by yoni6666** [justeat/JustLog#32]
line 41 - doesnt compile 
   **retVal = retVal.merged(with: inner.userInfo.flattened())** 

error : generic parameter "Value" could not be inferred

**Comment by ghost** [comment]
Hi @yoni6666, weird! We have CI building all the Pull Requests and all of them are green before we merge them. Commit 303aaf7 migrates JustLog to Swift 4, can you confirm you are on the same version or can you please provide more info?

**Comment by plantpurecode** [comment]
I am seeing this as well.

**Comment by TaugyStyle** [comment]
Hi , I do have the same issue, is there anything new on it ? JustLog v2.0.1.
Thanks for your time.

**Comment by dmahen** [comment]
This happens when the swift version is set to 3.2, it needs to be set to 4.0 like this, for just the JustLog framework if you don't want to convert your project to swift 4 ![this](https://i.imgur.com/hPZi86C.png)

**Comment by ghost** [comment]
Thanks @dmahen, you are right! We published version 2.0.2 with the `swift_version` set in the podspec (PR #35). cc @jacobrelkin @yoni6666 
Closing this as it's now resolved.
