### ISSUE TITLE
Question: how's this logger talking to Logstash?

### ISSUE THREAD

**Issue by tanis2000** [justeat/JustLog#39]
What kind of plugin and codec (and charset) should be defined on Logstash for JustLog to work correctly?

**Comment by tanis2000** [comment]
I figured out that my issue is that you need to turn SSL "on" in Logstash. 
But since I'm using a self-signed certificate I can't connect, so I had to change a few lines in AsyncSocketManager.

Specifically add the delegate for `didReceive trust`:

```
    func socket(_ sock: GCDAsyncSocket, didReceive trust: SecTrust, completionHandler: @escaping (Bool) -> Void) {
        completionHandler(true)
    }
```
and replace the line where it starts the TLS connection with the following:

```
        self.socket.startTLS([String(kCFStreamSSLPeerName): NSString(string: host), String(GCDAsyncSocketManuallyEvaluateTrust): NSString(string: "YES")])
```

Would it be possible to make this configurable instead?

**Comment by ghost** [comment]
Hi @tanis2000 this is not sorted with #37 (version JustLog v2.1.0) which funny enough arrived from the community at the same time of your message here. Are you working with @wolfAle by any chance? :D

**Comment by tanis2000** [comment]
@albertodebortoli-je now that's definitely funny :) I don't even know him but it looks like we got caught in the same situation at the same time :-P
BTW thanks for this project, it's helping sorting some issues out with one of my customers ;)

**Comment by ghost** [comment]
Ah... the universe! 😄 What a coincidence! Glad it helped.

**Comment by vahidsheikhalizadeh** [comment]
@tanis2000 I have the same problem and stumbled upon your answer, but somehow it did not solved the issue. could you please share with me the logstash configuration as well as what Have you done in your iOS app.
thanks
