### ISSUE TITLE
crash when logstashHost isn't set

### ISSUE THREAD

**Issue by augusteo** [justeat/JustLog#4]
during `setup()`, this will crash

`logstash = LogstashDestination(host: logstashHost, port: logstashPort, timeout: logstashTimeout, logActivity: logLogstashSocketActivity)`

because `logstashHost` is of type `String!`.

easy way to solve would be to just give a default of `""` like the other logstash vars.

**Comment by albertodebortoli** [comment]
@augusteo thanks for reporting! It should be now fixed with #5 and will hopefully be merged in soon

**Comment by federicocappelli** [comment]
Merged in master

**Comment by albertodebortoli** [comment]
This is now publicly available in trunk (v 1.1.0).

**Comment by Montrazul** [comment]
Wrong. It is still crasing.

```
logger.enableConsoleLogging = true;
logger.enableFileLogging = false;
logger.enableLogstashLogging = false;
        
logger.setup();
```

`fatal error: unexpectedly found nil while unwrapping an Optional value`

at 

```
Logger.forceSend(() -> ()) ->()
Logger.swift line 90: Logstash.forceSend(completionHandler)
```

**Comment by albertodebortoli** [comment]
@Montrazul you're right! #8 solves it.

**Comment by Montrazul** [comment]
When will it be merged into master?

**Comment by albertodebortoli** [comment]
@Montrazul it's done. v1.1.1 is on Cocoapods now.
