### ISSUE TITLE
Issue when building a static library 

### ISSUE THREAD

**Issue by pavan4** [justeat/JustLog#47]
Hello, 

When trying to package a static library with `JustLog` as a dependency in podspec, raises the following error 

`The Swift pod "JustLog" depends upon "CocoaAsyncSocket", which do not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set "use_modular_headers!" globally in your Podfile, or specify ":modular_headers => true" for particular dependencies.`

At the moment you have to specify `s.pod_target_xcconfig = { 'DEFINES_MODULE' => 'YES' }` flag in your podspec to get rid of this issue (see here : https://github.com/CocoaPods/CocoaPods/issues/7683 )

Could you please add this flag into your podspec?

**Comment by ghost** [comment]
Hi @pavan4 we made the change w/ #56 and published version 2.4.1.

**Comment by noelrappin** [comment]
Okay, look, it's probably user error, but I'm still seeing this in a build that's installing version 3.0.1. Any ideas what's wrong here?
