### ISSUE TITLE
Store some of the logs on the file and send the others to the server

### ISSUE THREAD

**Issue by tomasbek** [justeat/JustLog#49]
Hello,

I wanted to ask about the ability to store some of the logs on the file and the others on the server. For example,  all the messages of type **Info** I'd like to store on the file. However, when serious error occurs, I'd like to send the message of type **Error** to the server. How do I implement this?

Additionally, how do you send entire log file to the server (logz.io or Parse)? 

Thank you very much!

**Comment by ghost** [comment]
Hi @tomasbek, you can set the `minLevel` property of BaseDestination (which is the superclass of every destination) to define the log level.

JustLog currently has support for Logz.io: to send logs to it please see the relevant section in the [README](https://github.com/justeat/JustLog#sending-logs-to-logzio).
