### ISSUE TITLE
No support for Objective-C Projects?

### ISSUE THREAD

**Issue by komocode** [justeat/JustLog#50]
Since this is using SwiftyBeaver, this can't be used in Objective-C projects? Not sure why README shows that it does support Obj-C projects then.

**Comment by ghost** [comment]
HI @komocode, JustLog does support ObjC, in fact we use it in just fine in ObjC code. Just use the Logger methods with `_objc` suffix.
From the README:
```
[Logger.shared debug_objc:@"some message"];
[Logger.shared info_objc:@"some message" userInfo:someUserInfo];
[Logger.shared error_objc:@"some message" error:someError];
[Logger.shared error_objc:@"some message" error:someError userInfo:someUserInfo];
```

**Comment by komocode** [comment]
I tried installing via CocoaPods, but SwiftyBeaver doesn't seem to be working with Obj-C projects. I ended up going a different route, so I'll close.
