### ISSUE TITLE
Carthage

### ISSUE THREAD

**Issue by pdegouville** [justeat/JustLog#51]
Do you intend to give the possibility to install your framework with Carthage ? thks

**Comment by mark-anders** [comment]
I need that too.

**Comment by ghost** [comment]
Hi @pdegouville @mark-anders we don't use Carthage internally but we'd be happy to approve a PR with the changes to make it happen.

**Comment by mark-anders** [comment]
@albertodebortoli, sorry for not noticing, but #34 was resolved. So it seems like Carthage is already supported, no?

**Comment by ghost** [comment]
Ah! @mark-anders you are correct indeed! I didn't remember that.
