### ISSUE TITLE
Add Sematext / Elasticsearch as log output destination

### ISSUE THREAD

**Issue by otisg** [justeat/JustLog#62]
Elasticsearch has a simple HTTP REST API for ingesting data.
[Sematext](https://sematext.com/) exposes the Elasticsearch API, so by adding support for Elasticsearch output/destination we'd automatically get support for sending logs to Sematext, too.  2 birds... 

Being able to send logs to Sematext or Elasticsearch would be welcomed by a lot of people.

@albertodebortoli-je WDYT?

**Comment by ghost** [comment]
Hi @otisg, thank you for letting us know. It is definitely something that we can consider for the future, but right now it is not in our radar. Feel free to open a PR anyway!
