### ISSUE TITLE
Question: GELF format support

### ISSUE THREAD

**Issue by Dario-Gasquez** [justeat/JustLog#66]
Hi,

We found about JustLog looking for iOS logging solutions that provide ELK integration. An additional requirement we are looking for is GELF format support:
https://docs.graylog.org/en/3.0/pages/gelf.html#gelf-payload-specification

I am wondering if it would be trivial to add GELF support to JustLog or if on the other hand it would require the use of an additional third party library?

Thanks in advance!

**Comment by ilazakis** [comment]
From a first look at GELF  it looks like it’s feasible. `Logger` (the driving abstraction behind *JustLog*) assumes a number of [logstash specific things to be present](https://github.com/justeat/JustLog/blob/937cca0a2260bf5244fcfe0f5665b9ae85b95396/JustLog/Classes/Logger.swift#L42). 

That said, extending the library to support new targets should be fairly straightforward, one could add the `GELF` specific config and add an extra `GELF` check to the [existing ones](https://github.com/justeat/JustLog/blob/937cca0a2260bf5244fcfe0f5665b9ae85b95396/JustLog/Classes/Logger.swift#L79)

**Comment by Dario-Gasquez** [comment]
Great!, that sounds promising. Thanks for the prompt reply.
