### ISSUE TITLE
Add file & function to Console logging

### ISSUE THREAD

**Issue by philipp-serfling** [justeat/JustLog#68]
Is there any way to configure the Console logging in a way that it shows which file and which function caused the log?

This would be really handy.

**Comment by gigisommo** [comment]
Yes, there is. You can change the format string specified for the different destinations `console` `logstash` or `file` that you can find in `Logger.swift` according to the `SwiftyBeaver` format documentation that you can find [here](https://docs.swiftybeaver.com/article/20-custom-format), then you need to pass the `#file`, `#function` and `#line` to the functions that you're using to log according to the `Logging` protocol defined in `Logging.swift`. 
I hope that this is helpful, let me know if you have any doubt.

**Comment by philipp-serfling** [comment]
That worked, thank you!
I have just enriched the message string with these variables.

`"\(message) ➡️ AT: \((String(describing:file) as NSString).lastPathComponent):\(function):\(line)"`
