### ISSUE TITLE
Loglevel?

### ISSUE THREAD

**Issue by Appelg** [justeat/JustLog#86]
I can't figure out if it's possible to configure a minimum loglevel to send?
I want to disable debug/info-logs when going to production.

**Comment by albertodebortoli** [comment]
Hi @Appelg yes you can on any destination (via the `BaseDestination`'s `minLevel` property).

It's done via SwiftyBeaver, not JustLog per se.

E.g.
```
let minLogLevel: SwiftyBeaver.Level
switch <yourConfiguration> {
    case "verbose":
        minLogLevel = .verbose
    case "debug":
        minLogLevel = .debug
    case "info":
        minLogLevel = .info
    case "warning":
        minLogLevel = .warning
    case "error":
        minLogLevel = .error
    default:
        minLogLevel = .verbose
}
Logger.shared.logstash.minLevel = minLogLevel
```

**Comment by Appelg** [comment]
Totally missed that, thanks!
