### ISSUE TITLE
Question on Offline Logging and re-upload when internet connection is available

### ISSUE THREAD

**Issue by AlfredKallas** [justeat/JustLog#90]
Hello, 

Does justLog supports saving logs to a file or a  database and then uploading the logs to Elasticsearch or even a custom server when internet connection is available and based on some conditions for example : 

- perdiodic timer

- when the size of the logs reach a certain size ? 

After checking the code base of the library, i conclude that this is not provided, if i am not mistaken can i add this functionality to the Library myself ?

Thank you for your replies !

**Comment by gigisommo** [comment]
Hi @AlfredKallas, JustLog doesn't offer those features and we don't have plans to add them. but the library is open source so you can fork it and add it yourself!

**Comment by albertodebortoli** [comment]
I'm gonna go ahead and close this as we are deprecating the component and archiving the repo.
