### ISSUE TITLE
Is it possible to send logs to a HTTP endpoint ?

### ISSUE THREAD

**Issue by lolitha-aet** [justeat/JustLog#91]
Thank you for the awesome library @gigisommo .
Is it possible to send logs to a HTTP endpoint rather than using socket communication ?

**Comment by gigisommo** [comment]
Hi @lolitha-aet,
thank you for your question and interest. Sadly JustLog does not support it out of the box. Under the hood JustLog uses [SwiftyBeaver](https://github.com/SwiftyBeaver/SwiftyBeaver) and you can take a look at it. JustLog remove part of SwiftyBeaver flexibility to make it easier to be up and running quickly. I hope that this will help.

**Comment by albertodebortoli** [comment]
I'm gonna go ahead and close this as we are deprecating the component and archiving the repo.

**Comment by albertodebortoli** [comment]
I'm gonna go ahead and close this as we are deprecating the component and archiving the repo.
