### ISSUE TITLE
Is JustLog available or validated on macOS?

### ISSUE THREAD

**Issue by stevekellogg** [justeat/JustLog#97]
Hello folks.

I'm looking for a good solution for exporting logs to an ELK stack (I'm currently using Elastic cloud), but I sometimes need to support macOS in my apps.  I'm about to attempt a validation to see if JustLog is suitable, but I thought I'd ask whether you folks have any insights that might be helpful.

Thanks in advance.

**Comment by gigisommo** [comment]
Hi @stevekellogg,

sadly we didn't try it out on macOS yet. JustLog uses [SwiftyBeaver](https://github.com/SwiftyBeaver/SwiftyBeaver) under the hood and it has support for macOS. You can give it a try. I don't see any obvious reason why it shouldn't work.

**Comment by stevekellogg** [comment]
Thanks very much!  I'll keep you posted with any findings.

**Comment by albertodebortoli** [comment]
I'm gonna go ahead and close this as we are deprecating the component and archiving the repo.
